### ISSUE TITLE
jsRofex.js debería llamarse Rofexjs.js

### ISSUE THREAD

**Issue by gustavoghp87** [matbarofex/jsRofex#3]
Cuando quiero usar el módulo tengo un "Error: Cannot find module '/app/node_modules/rofexjs/Rofexjs.js' "

que se soluciona simplemente cambiándole el nombre a jsRofex.js por Rofexjs.js pero en servicios web como Heroku se complica un poco

**Comment by davidlbt** [comment]
Otra solución es editar el package.json del modulo, y cambiar el nombre del main.
